name: Development Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build and run docker-compose
        run: docker-compose up --build -d
